"""Centralized configuration constants."""

import os
from pathlib import Path

SCAN_VERSION = "v3.0.0"
SCORING_VERSION = "v3.0.0"
RECOMMENDATION_VERSION = "v1.0.0"
UNIVERSE_SELECTION_VERSION = "v1.0.0"

FLASK_SECRET_KEY = os.environ.get("FLASK_SECRET_KEY", "")

CACHE_DIR = Path(__file__).parent / "cache"
CACHE_DIR.mkdir(exist_ok=True)
CACHE_FILE = CACHE_DIR / "scan_results.json"

CACHE_TTL_HOURS = 6
DATA_LOOKBACK_DAYS = 365
BENCHMARK_LOOKBACK_DAYS = 60
_ON_RAILWAY = bool(os.environ.get("RAILWAY_ENVIRONMENT"))

MAX_WORKERS = 3 if _ON_RAILWAY else 4
MAX_RAW_SCORE = 380
TOP_N_RESULTS = 3000
DASHBOARD_MAX_RESULTS = int(os.getenv("DASHBOARD_MAX_RESULTS", "500"))

BATCH_SIZE = 30 if _ON_RAILWAY else 80
BATCH_DELAY = 20 if _ON_RAILWAY else 10

AUTO_SCAN_INTERVAL = int(os.getenv("AUTO_SCAN_INTERVAL", "60"))
ATR_SL_MULTIPLIER = 2.0
TARGET_USES_RESISTANCE = True

HC_MIN_SCORE = 55
HC_MIN_SIGNALS_BULLISH = 5
HC_RSI_RANGE = (40, 70)
HC_DELIVERY_MIN = 40
HC_ATR_RANGE = (1.5, 5.5)
HC_RISK_MAX = 40
HC_REQUIRE_MACD_BULLISH = False
HC_REQUIRE_VOLUME = 1.0
HC_MIN_RISK_REWARD = 2.2

BP_RSI_MAX = 40
BP_VOLUME_MIN = 1.2
BP_DELIVERY_MIN = 45
BP_WEEK1_MAX_LOSS = -2.0
BP_MACD_BULLISH = True
BP_TARGET_PCT = 10.0

USE_UNIVERSE_ENGINE = os.getenv("USE_UNIVERSE_ENGINE", "0") == "1"
AUTO_SCAN_ENABLED_DEFAULT = os.getenv("AUTO_SCAN_ENABLED_DEFAULT", "0") == "1"
SCAN_BATCH_SIZE = int(os.getenv("SCAN_BATCH_SIZE", "50"))
MAX_SCAN_WORKERS = min(int(os.getenv("MAX_SCAN_WORKERS", "2")), 2)

UNIVERSE_MIN_MCAP_CR = float(os.getenv("UNIVERSE_MIN_MCAP_CR", "1500"))
UNIVERSE_MIN_AVG_TURNOVER_CR = float(os.getenv("UNIVERSE_MIN_AVG_TURNOVER_CR", "5"))
UNIVERSE_MIN_AVG_VOLUME = int(os.getenv("UNIVERSE_MIN_AVG_VOLUME", "100000"))
UNIVERSE_MIN_PRICE = float(os.getenv("UNIVERSE_MIN_PRICE", "20"))
MASTER_SYNC_INTERVAL_DAYS = int(os.getenv("MASTER_SYNC_INTERVAL_DAYS", "14"))
UNIVERSE_REBUILD_HOUR = 8
UNIVERSE_REBUILD_MINUTE = 30
